[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi~=0.118.2",
    "ldap3~=2.9.1",
    "pydantic~=2.12.0",
    "python3-ldap~=0.9.8.4",
    "sqlalchemy[asyncio]>=2.0.44",
    "uvicorn~=0.37.0",
]
